### ISSUE TITLE
Multiple runs using the same random number seed are not identical.

### ISSUE THREAD

**Issue by hawson** [DangerBlack/fantasy-city-planner#6]
They are similar, but the placement of most non-labeled buildings (and even some labeled ones) is random.

**Comment by hawson** [comment]
![mappa_35](https://cloud.githubusercontent.com/assets/361383/10532291/b7b00c88-738a-11e5-8160-a4f8c8fba86f.png)
![mappa_36](https://cloud.githubusercontent.com/assets/361383/10532293/bb9d97c0-738a-11e5-9422-993819a9753c.png)
![mappa_37](https://cloud.githubusercontent.com/assets/361383/10532295/bdbf2f78-738a-11e5-8a6b-b8973b031769.png)

**Comment by DangerBlack** [comment]
I thinks it may depends on how python save list and dictionary, they can be ordered as they like it.
I had a similar problem in android with java.

**Comment by hawson** [comment]
Makes sense.  Lists are ordered, dictionaries aren't.  Truly consistent results would be nice, but would probably mean refactoring a bunch of code.  I suppose if the minor building placement (i.e. unlabeled random houses) happened at the very end, it won't matter much.

**Comment by DangerBlack** [comment]
> Makes sense. Lists are ordered, dictionaries aren't. **Truly consistent results would be nice**, but would probably mean refactoring a bunch of code. I suppose if the minor building placement (i.e. unlabeled random houses) happened at the very end, it won't matter much.

We have to work on this issue but more tests are needed for discover why this happens.

``` python
test=[4,1,5,8]
end=list(test)
print(end)
#I had to test this...
```

no no no this is not the problem!!!

it's a race condition on random!!!!

Two different ran has two different scheduling! So buildings are moved randomly but each random happens in a different timeslice

**Comment by DangerBlack** [comment]
A possible solution is to sends N differents seed for each run, so each run is thread safe with his own random.
